/* The following code was generated by JFlex 1.7.0 */

/*--------- 1ra Area: Codigo de Usuario ---------*/

//--------> Paquetes e importaciones
package Analizadores;
import java_cup.runtime.*;
import Estructuras.Cola;
import Modelos.Errores;

/*--------- 2da Area: Opciones y Declaraciones ---------*/


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Lexico_Reportes.jflex</tt>
 */
public class Analisis_Lexico_Reportes implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 39,  8,  8,  8,  8,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    39, 15,  4,  0,  0,  0,  0,  0, 10, 11,  9,  0, 16,  1,  3,  7, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  0, 12, 13, 17, 14,  0, 
     0, 18, 36, 20, 35, 27, 38, 37, 21, 23,  5,  5, 26, 30, 28, 25, 
    34,  5, 19, 32, 33, 29, 24,  5,  5,  5,  5,  0,  0,  0,  0,  6, 
     0, 18, 36, 20, 35, 27, 38, 37, 21, 23,  5,  5, 26, 30, 28, 25, 
    34,  5, 19, 32, 33, 29, 24,  5,  5,  5,  5,  0,  6,  0,  0,  0, 
     0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    39,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\1\1\3\1\1\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\2\3"+
    "\1\1\4\3\1\1\3\3\2\0\1\15\1\16\1\0"+
    "\3\3\1\0\4\3\1\0\3\3\1\2\1\0\3\3"+
    "\1\0\4\3\1\0\3\3\1\17\3\3\1\0\4\3"+
    "\1\0\3\3\1\0\3\3\1\0\4\3\2\20\1\3"+
    "\1\0\1\3\1\0\1\3\1\21\1\22\1\0\3\3"+
    "\1\0\2\3\1\0\1\3\2\23\1\0\1\3\1\0"+
    "\3\3\1\0\1\3\1\0\1\3\1\0\1\3\2\24"+
    "\2\25\1\0\2\3\2\26\2\27\2\30\2\31\1\0"+
    "\1\3\1\0\1\3\2\32";

  private static int [] zzUnpackAction() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\360\0\50"+
    "\0\50\0\50\0\50\0\50\0\50\0\50\0\50\0\50"+
    "\0\u0118\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230"+
    "\0\u0258\0\u0280\0\u02a8\0\u02d0\0\240\0\50\0\u02f8\0\u0320"+
    "\0\u0348\0\u0370\0\u0398\0\u03c0\0\u03e8\0\u0410\0\u0438\0\u0460"+
    "\0\u0488\0\u04b0\0\u04d8\0\u0500\0\u02d0\0\u0528\0\u0550\0\u0578"+
    "\0\u05a0\0\u05c8\0\u05f0\0\u0618\0\u0640\0\u0668\0\u0690\0\u06b8"+
    "\0\u06e0\0\u0708\0\50\0\u0730\0\u0758\0\u0780\0\u07a8\0\u07d0"+
    "\0\u07f8\0\u0820\0\u0848\0\u0870\0\u0898\0\u08c0\0\u08e8\0\u0910"+
    "\0\u0938\0\u0960\0\u0988\0\u09b0\0\u09d8\0\u0a00\0\u0a28\0\u0a50"+
    "\0\50\0\310\0\u0a78\0\u0aa0\0\u0ac8\0\u0af0\0\u0b18\0\310"+
    "\0\u0b40\0\u0b68\0\u0b90\0\u0bb8\0\u0be0\0\u0c08\0\u0c30\0\u0c58"+
    "\0\u0c80\0\u0ca8\0\50\0\310\0\u0cd0\0\u0cf8\0\u0d20\0\u0d48"+
    "\0\u0d70\0\u0d98\0\u0dc0\0\u0de8\0\u0e10\0\u0e38\0\u0e60\0\u0e88"+
    "\0\50\0\310\0\50\0\310\0\u0eb0\0\u0ed8\0\u0f00\0\50"+
    "\0\310\0\50\0\310\0\50\0\310\0\50\0\310\0\u0f28"+
    "\0\u0f50\0\u0f78\0\u0fa0\0\50\0\310";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\2\1\7"+
    "\1\10\1\2\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\6\1\22\1\6\1\23\1\24"+
    "\1\6\1\25\1\26\1\6\1\27\2\6\1\30\1\31"+
    "\1\6\1\32\2\6\1\33\1\6\1\10\52\0\1\4"+
    "\47\0\1\4\1\34\44\0\4\35\1\36\43\35\2\0"+
    "\1\6\2\0\2\6\13\0\4\6\1\0\10\6\1\0"+
    "\7\6\10\0\1\37\1\0\1\40\40\0\1\6\2\0"+
    "\2\6\13\0\1\6\1\41\2\6\1\0\10\6\1\0"+
    "\7\6\3\0\1\6\2\0\2\6\13\0\1\42\3\6"+
    "\1\0\2\6\1\43\5\6\1\0\7\6\37\0\1\44"+
    "\13\0\1\6\2\0\2\6\13\0\4\6\1\0\7\6"+
    "\1\45\1\0\7\6\3\0\1\6\2\0\2\6\13\0"+
    "\4\6\1\0\10\6\1\0\4\6\1\46\2\6\3\0"+
    "\1\6\2\0\2\6\13\0\4\6\1\0\4\6\1\47"+
    "\3\6\1\0\7\6\3\0\1\6\2\0\2\6\13\0"+
    "\4\6\1\0\6\6\1\50\1\6\1\0\7\6\36\0"+
    "\1\51\14\0\1\6\2\0\2\6\13\0\4\6\1\0"+
    "\6\6\1\52\1\6\1\0\7\6\3\0\1\6\2\0"+
    "\2\6\13\0\1\6\1\53\2\6\1\0\10\6\1\0"+
    "\7\6\3\0\1\6\2\0\2\6\13\0\1\6\1\54"+
    "\2\6\1\0\10\6\1\0\7\6\3\0\1\55\45\0"+
    "\10\37\1\0\37\37\11\40\1\56\36\40\2\0\1\6"+
    "\2\0\2\6\13\0\2\6\1\57\1\6\1\0\10\6"+
    "\1\0\7\6\3\0\1\6\2\0\2\6\13\0\4\6"+
    "\1\0\10\6\1\0\3\6\1\60\3\6\3\0\1\6"+
    "\2\0\2\6\13\0\4\6\1\0\5\6\1\61\2\6"+
    "\1\0\7\6\43\0\1\62\7\0\1\6\2\0\2\6"+
    "\13\0\4\6\1\0\10\6\1\0\2\6\1\63\4\6"+
    "\3\0\1\6\2\0\2\6\13\0\4\6\1\0\10\6"+
    "\1\0\1\6\1\64\5\6\3\0\1\6\2\0\2\6"+
    "\13\0\4\6\1\0\4\6\1\65\3\6\1\0\7\6"+
    "\3\0\1\6\2\0\2\6\13\0\4\6\1\0\7\6"+
    "\1\66\1\0\7\6\37\0\1\67\13\0\1\6\2\0"+
    "\2\6\13\0\4\6\1\0\7\6\1\70\1\0\7\6"+
    "\3\0\1\6\2\0\2\6\13\0\4\6\1\0\2\6"+
    "\1\71\5\6\1\0\7\6\3\0\1\6\2\0\2\6"+
    "\13\0\1\72\3\6\1\0\10\6\1\0\7\6\1\0"+
    "\7\40\1\73\1\40\1\56\36\40\2\0\1\6\2\0"+
    "\2\6\13\0\3\6\1\74\1\0\10\6\1\0\7\6"+
    "\3\0\1\6\2\0\2\6\13\0\4\6\1\0\4\6"+
    "\1\75\3\6\1\0\7\6\3\0\1\6\2\0\2\6"+
    "\13\0\4\6\1\0\10\6\1\0\1\6\1\76\5\6"+
    "\24\0\1\77\26\0\1\6\2\0\2\6\13\0\1\6"+
    "\1\100\2\6\1\0\10\6\1\0\7\6\3\0\1\6"+
    "\2\0\2\6\13\0\4\6\1\0\4\6\1\101\3\6"+
    "\1\0\7\6\3\0\1\6\2\0\2\6\13\0\1\6"+
    "\1\102\2\6\1\0\10\6\1\0\7\6\3\0\1\6"+
    "\2\0\2\6\13\0\4\6\1\0\4\6\1\103\3\6"+
    "\1\0\7\6\23\0\1\104\27\0\1\6\2\0\2\6"+
    "\13\0\1\105\3\6\1\0\10\6\1\0\7\6\3\0"+
    "\1\6\2\0\2\6\13\0\4\6\1\0\7\6\1\106"+
    "\1\0\7\6\3\0\1\6\2\0\2\6\13\0\4\6"+
    "\1\0\10\6\1\0\6\6\1\107\3\0\1\6\2\0"+
    "\2\6\13\0\4\6\1\110\1\111\7\6\1\0\7\6"+
    "\3\0\1\6\2\0\2\6\13\0\4\6\1\0\5\6"+
    "\1\112\2\6\1\0\7\6\3\0\1\6\2\0\2\6"+
    "\13\0\1\113\3\6\1\0\10\6\1\0\7\6\27\0"+
    "\2\114\22\0\1\6\2\0\2\6\13\0\4\6\1\114"+
    "\1\115\7\6\1\0\7\6\3\0\1\6\2\0\2\6"+
    "\13\0\4\6\1\0\5\6\1\116\2\6\1\0\7\6"+
    "\3\0\1\6\2\0\2\6\13\0\1\117\3\6\1\0"+
    "\10\6\1\0\7\6\3\0\1\6\2\0\2\6\13\0"+
    "\1\6\1\120\2\6\1\0\10\6\1\0\7\6\24\0"+
    "\1\121\26\0\1\6\2\0\2\6\13\0\1\6\1\122"+
    "\2\6\1\0\10\6\1\0\7\6\3\0\1\6\2\0"+
    "\2\6\13\0\4\6\1\0\4\6\1\123\3\6\1\0"+
    "\7\6\3\0\1\6\2\0\2\6\13\0\4\6\1\124"+
    "\1\125\7\6\1\0\7\6\31\0\1\126\21\0\1\6"+
    "\2\0\2\6\13\0\4\6\1\0\1\6\1\127\6\6"+
    "\1\0\7\6\3\0\1\6\2\0\2\6\13\0\1\130"+
    "\3\6\1\0\10\6\1\0\7\6\3\0\1\6\2\0"+
    "\2\6\13\0\1\6\1\131\2\6\1\0\10\6\1\0"+
    "\7\6\37\0\1\132\13\0\1\6\2\0\2\6\13\0"+
    "\4\6\1\0\7\6\1\133\1\0\7\6\3\0\1\6"+
    "\2\0\2\6\13\0\4\6\1\0\4\6\1\134\3\6"+
    "\1\0\7\6\3\0\1\6\2\0\2\6\13\0\1\6"+
    "\1\135\2\6\1\0\10\6\1\0\7\6\3\0\1\6"+
    "\2\0\2\6\13\0\4\6\1\136\1\137\7\6\1\0"+
    "\7\6\3\0\1\6\2\0\2\6\13\0\4\6\1\0"+
    "\10\6\1\0\3\6\1\140\3\6\25\0\1\141\25\0"+
    "\1\6\2\0\2\6\13\0\2\6\1\142\1\6\1\0"+
    "\10\6\1\0\7\6\32\0\1\143\20\0\1\6\2\0"+
    "\2\6\13\0\4\6\1\0\2\6\1\144\5\6\1\0"+
    "\7\6\3\0\1\6\2\0\2\6\13\0\4\6\1\0"+
    "\10\6\1\145\1\146\6\6\27\0\2\147\22\0\1\6"+
    "\2\0\2\6\13\0\4\6\1\147\1\150\7\6\1\0"+
    "\7\6\3\0\1\6\2\0\2\6\13\0\1\6\1\151"+
    "\2\6\1\0\10\6\1\0\7\6\3\0\1\6\2\0"+
    "\2\6\13\0\2\6\1\152\1\6\1\0\10\6\1\0"+
    "\7\6\25\0\1\153\25\0\1\6\2\0\2\6\13\0"+
    "\2\6\1\154\1\6\1\0\10\6\1\0\7\6\3\0"+
    "\1\6\2\0\2\6\13\0\4\6\1\155\1\156\7\6"+
    "\1\0\7\6\23\0\1\157\27\0\1\6\2\0\2\6"+
    "\13\0\1\160\3\6\1\0\10\6\1\0\7\6\27\0"+
    "\2\161\22\0\1\6\2\0\2\6\13\0\4\6\1\161"+
    "\1\162\7\6\1\0\7\6\24\0\1\163\26\0\1\6"+
    "\2\0\2\6\13\0\1\6\1\164\2\6\1\0\10\6"+
    "\1\0\7\6\3\0\1\6\2\0\2\6\13\0\4\6"+
    "\1\0\10\6\1\165\1\166\6\6\3\0\1\6\2\0"+
    "\2\6\13\0\3\6\1\167\1\0\10\6\1\0\7\6"+
    "\32\0\1\170\20\0\1\6\2\0\2\6\13\0\4\6"+
    "\1\0\2\6\1\171\5\6\1\0\7\6\32\0\1\172"+
    "\20\0\1\6\2\0\2\6\13\0\4\6\1\0\2\6"+
    "\1\173\5\6\1\0\7\6\24\0\1\174\26\0\1\6"+
    "\2\0\2\6\13\0\1\6\1\175\2\6\1\0\10\6"+
    "\1\0\7\6\27\0\2\176\22\0\1\6\2\0\2\6"+
    "\13\0\4\6\1\176\1\177\7\6\1\0\7\6\3\0"+
    "\1\6\2\0\2\6\13\0\4\6\1\200\1\201\7\6"+
    "\1\0\7\6\31\0\1\202\21\0\1\6\2\0\2\6"+
    "\13\0\4\6\1\0\1\6\1\203\6\6\1\0\7\6"+
    "\32\0\1\204\20\0\1\6\2\0\2\6\13\0\4\6"+
    "\1\0\2\6\1\205\5\6\1\0\7\6\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4040];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\11\11\13\1\2\0\1\11\1\1"+
    "\1\0\3\1\1\0\4\1\1\0\4\1\1\0\3\1"+
    "\1\0\4\1\1\0\3\1\1\11\3\1\1\0\4\1"+
    "\1\0\3\1\1\0\3\1\1\0\4\1\1\11\2\1"+
    "\1\0\1\1\1\0\3\1\1\0\3\1\1\0\2\1"+
    "\1\0\1\1\1\11\1\1\1\0\1\1\1\0\3\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\11\1\1"+
    "\1\11\1\1\1\0\2\1\1\11\1\1\1\11\1\1"+
    "\1\11\1\1\1\11\1\1\1\0\1\1\1\0\1\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //--------> Codigo de Usuario en sintaxis Java
    public Cola ErroresLexicos = new Cola();



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Analisis_Lexico_Reportes(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(Simbolos_Reportes.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error Lexico Lexema: " + yytext() + " Fila: " + yyline + " Columna: " + yycolumn);
                                        Errores error = new Errores(yytext(),yyline,yycolumn
                                            ,"Error Lexico, No Especificado en el Lenguaje","Lexico");
                                        ErroresLexicos.insertar(error);
            } 
            // fall through
          case 27: break;
          case 2: 
            { return new Symbol(Simbolos_Reportes.numero, yycolumn, yyline, yytext());
            } 
            // fall through
          case 28: break;
          case 3: 
            { return new Symbol(Simbolos_Reportes.ident, yycolumn, yyline, yytext());
            } 
            // fall through
          case 29: break;
          case 4: 
            { /* Espacios en blanco se ignoran */
            } 
            // fall through
          case 30: break;
          case 5: 
            { return new Symbol(Simbolos_Reportes.parenteA, yycolumn, yyline, yytext());
            } 
            // fall through
          case 31: break;
          case 6: 
            { return new Symbol(Simbolos_Reportes.parenteC, yycolumn, yyline, yytext());
            } 
            // fall through
          case 32: break;
          case 7: 
            { return new Symbol(Simbolos_Reportes.puntoComa, yycolumn, yyline, yytext());
            } 
            // fall through
          case 33: break;
          case 8: 
            { return new Symbol(Simbolos_Reportes.menorQue, yycolumn, yyline, yytext());
            } 
            // fall through
          case 34: break;
          case 9: 
            { return new Symbol(Simbolos_Reportes.mayorQue, yycolumn, yyline, yytext());
            } 
            // fall through
          case 35: break;
          case 10: 
            { return new Symbol(Simbolos_Reportes.diferente, yycolumn, yyline, yytext());
            } 
            // fall through
          case 36: break;
          case 11: 
            { return new Symbol(Simbolos_Reportes.coma, yycolumn, yyline, yytext());
            } 
            // fall through
          case 37: break;
          case 12: 
            { return new Symbol(Simbolos_Reportes.igual, yycolumn, yyline, yytext());
            } 
            // fall through
          case 38: break;
          case 13: 
            { return new Symbol(Simbolos_Reportes.cadena, yycolumn, yyline, yytext());
            } 
            // fall through
          case 39: break;
          case 14: 
            { return new Symbol(Simbolos_Reportes.comentarioLinea, yycolumn, yyline, yytext());
            } 
            // fall through
          case 40: break;
          case 15: 
            { return new Symbol(Simbolos_Reportes.comentarioMultiLinea, yycolumn, yyline, yytext());
            } 
            // fall through
          case 41: break;
          case 16: 
            { return new Symbol(Simbolos_Reportes.sumar, yycolumn, yyline, yytext());
            } 
            // fall through
          case 42: break;
          case 17: 
            { return new Symbol(Simbolos_Reportes.tipoCadena, yycolumn, yyline, yytext());
            } 
            // fall through
          case 43: break;
          case 18: 
            { return new Symbol(Simbolos_Reportes.contar, yycolumn, yyline, yytext());
            } 
            // fall through
          case 44: break;
          case 19: 
            { return new Symbol(Simbolos_Reportes.tipoArchivo, yycolumn, yyline, yytext());
            } 
            // fall through
          case 45: break;
          case 20: 
            { return new Symbol(Simbolos_Reportes.contarSi, yycolumn, yyline, yytext());
            } 
            // fall through
          case 46: break;
          case 21: 
            { return new Symbol(Simbolos_Reportes.imprimir, yycolumn, yyline, yytext());
            } 
            // fall through
          case 47: break;
          case 22: 
            { return new Symbol(Simbolos_Reportes.tipoNumerico, yycolumn, yyline, yytext());
            } 
            // fall through
          case 48: break;
          case 23: 
            { return new Symbol(Simbolos_Reportes.promedio, yycolumn, yyline, yytext());
            } 
            // fall through
          case 49: break;
          case 24: 
            { return new Symbol(Simbolos_Reportes.graficar, yycolumn, yyline, yytext());
            } 
            // fall through
          case 50: break;
          case 25: 
            { return new Symbol(Simbolos_Reportes.obtenerSi, yycolumn, yyline, yytext());
            } 
            // fall through
          case 51: break;
          case 26: 
            { return new Symbol(Simbolos_Reportes.leerArchivo, yycolumn, yyline, yytext());
            } 
            // fall through
          case 52: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
