
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos_Reportes {
  /* terminals */
  public static final int parenteA = 2;
  public static final int cadena = 24;
  public static final int promedio = 15;
  public static final int coma = 8;
  public static final int numero = 25;
  public static final int tipoArchivo = 10;
  public static final int comentarioMultiLinea = 22;
  public static final int imprimir = 19;
  public static final int sumar = 13;
  public static final int contarSi = 16;
  public static final int comentarioLinea = 21;
  public static final int ident = 23;
  public static final int igual = 9;
  public static final int EOF = 0;
  public static final int obtenerSi = 18;
  public static final int error = 1;
  public static final int contar = 14;
  public static final int tipoCadena = 17;
  public static final int tipoNumerico = 12;
  public static final int graficar = 20;
  public static final int leerArchivo = 11;
  public static final int diferente = 7;
  public static final int puntoComa = 4;
  public static final int menorQue = 5;
  public static final int mayorQue = 6;
  public static final int parenteC = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "parenteA",
  "parenteC",
  "puntoComa",
  "menorQue",
  "mayorQue",
  "diferente",
  "coma",
  "igual",
  "tipoArchivo",
  "leerArchivo",
  "tipoNumerico",
  "sumar",
  "contar",
  "promedio",
  "contarSi",
  "tipoCadena",
  "obtenerSi",
  "imprimir",
  "graficar",
  "comentarioLinea",
  "comentarioMultiLinea",
  "ident",
  "cadena",
  "numero"
  };
}

