
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos_Datos {
  /* terminals */
  public static final int corcheteA = 2;
  public static final int llaveC = 5;
  public static final int llaveA = 4;
  public static final int coma = 6;
  public static final int claves = 9;
  public static final int comentarioMultiLinea = 13;
  public static final int registros = 10;
  public static final int cadena = 11;
  public static final int EOF = 0;
  public static final int numero = 8;
  public static final int error = 1;
  public static final int comentarioLinea = 12;
  public static final int corcheteC = 3;
  public static final int igual = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "corcheteA",
  "corcheteC",
  "llaveA",
  "llaveC",
  "coma",
  "igual",
  "numero",
  "claves",
  "registros",
  "cadena",
  "comentarioLinea",
  "comentarioMultiLinea"
  };
}

