
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.HTML;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int cerrar = 16;
  public static final int cadena = 15;
  public static final int texto = 19;
  public static final int inicioHead = 8;
  public static final int inicioTitle = 6;
  public static final int inicioDiv = 12;
  public static final int inicioHtml = 2;
  public static final int inicioBody = 4;
  public static final int finDiv = 13;
  public static final int igual = 18;
  public static final int EOF = 0;
  public static final int finNoufe = 11;
  public static final int id = 14;
  public static final int finHead = 9;
  public static final int error = 1;
  public static final int abrir = 17;
  public static final int finBody = 5;
  public static final int finHtml = 3;
  public static final int finTitle = 7;
  public static final int inicioNoufe = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "inicioHtml",
  "finHtml",
  "inicioBody",
  "finBody",
  "inicioTitle",
  "finTitle",
  "inicioHead",
  "finHead",
  "inicioNoufe",
  "finNoufe",
  "inicioDiv",
  "finDiv",
  "id",
  "cadena",
  "cerrar",
  "abrir",
  "igual",
  "texto"
  };
}

